package:
  name: ros-noetic-libg2o
  version: 2020.5.3
source:
  git_url: https://github.com/ros-gbp/libg2o-release.git
  git_rev: release/noetic/libg2o/2020.5.3-1
  folder: ros-noetic-libg2o/src/work
  patches:
    - patch/ros-noetic-libg2o.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 15
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - boost
    - eigen
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
    - suitesparse
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - boost
    - eigen
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
    - suitesparse
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
